name: Apply Terraform Plan
on:
  workflow_call:
    inputs:
      WORK_DIR:
        required: false
        type: string
        default: ./
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_ASSUMED_ROLE:
        required: true

jobs:
  plan:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ASSUMED_ROLE }}
          role-duration-seconds: 900
          role-skip-session-tagging: true

      - name: Checkout Codebase
        uses: actions/checkout@v3.1.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.3.1

      - name: Initialize Terraform
        run: terraform init -input=false -backend=false

      - name: Apply Terraform Plan
        run: terraform apply -input=false -auto-approve
