name: Docker Build

on: 
  workflow_call:
    inputs:
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      working-directory:
        required: false
        type: string
        default: "."
      repository:
        required: true
        type: string
      image-name:
        required: true
        type: string
      tag:
        required: true
        type: string
      repository-username:
        required: false
        type: string
      publish:
        required: false
        type: boolean
        default: false
      build-args:
        required: false
        type: string
      publish-args:
        required: false
        type: string
    secrets:
      repository-password:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build ${{ inputs.working-directory }} --file ${{ inputs.dockerfile }} --tag ${{ inputs.repository }}/${{ inputs.image-name }}:${{ inputs.tag }} ${{ inputs.build-args }}

  publish:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish }}
    steps:

    - name: Login
      if: ${{ inputs.repository-username }}
      run: docker login ${{ inputs.repository }} -u ${{ inputs.repository-username }} -p ${{ secrets.repository-password }}

    - name: Publish
      run: docker push ${{ inputs.repostory }}/${{ inputs.image-name }}:${{ inputs.tag }} ${{ inputs.publish-args }}