on:
  workflow_call:
    inputs:
      goVersion:
        required: false
        type: string
        description: "Golang version"
        default: "1.17"
      testCommand:
        required: false
        type: string
        description: "Command to run tests"
        default: "go test -v ./..."
      workingDirectory:
        required: false
        type: string
        default: "."
        description: "Working directory"
      uploadToCodeCov:
        required: false
        type: boolean
        description: "Send code coverage output to CodeCov"
        default: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.goVersion }}

      - name: Download Dependencies
        working-directory: ${{ inputs.workingDirectory }}
        run: go mod download

      - name: Test
        working-directory: ${{ inputs.workingDirectory }}
        run: |
          ${{ inputs.testCommand }}

      - name: Upload Code Coverage
        if: ${{ inputs.uploadToCodeCov }}
        uses: codecov/codecov-action@v2

      - name: Build
        working-directory: ${{ inputs.workingDirectory }}
        run: go build -v .
