name: Terraform Format Check
on:
  workflow_call:
    inputs:
      WORK_DIR:
        required: true
        type: string

jobs:
  fmt:
    name: Check Terraform formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3.1.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.3.1

      - name: Initialize Terraform
        run: terraform init -input=false -backend=false

      - name: Run fmt with diffs 
        run: terraform fmt -check -diff ${{ inputs.WORK_DIR }}

      - name: Validate Terraform
        run: terraform validate
